### ISSUE TITLE
Not an issue but I want to show interest

### ISSUE THREAD

**Issue by sebastianha** [fbeek/pimatic-maxcul#1]
Hi,

this is not an issue but I just want to let you know that I would love to see your plugin for pimatic fully functional.

Currently, I am using FHEM with cul but I am not very satisfied with it. The problem is that any other home automation software written for nodejs does not really support max thermostats / switches or utilizes the LAN gateway.

So please go on, continue your work – the world needs it ;)

**Comment by fbeek** [comment]
Hi,

auf Grund der späten Stunde und deines Namens gehe ich mal davon aus das du auch Deutsch verstehst :-D falls nicht bitte ich das zu entschuldigen, dann sag bescheid und ich melde mich auf Englisch.

Erstmal danke für deine Aufbauenden Worte :-)

Ich hatte das gleiche Problem mit FHEM, ich muss sagen ich finde es einfach furchtbar...bei Perl fängt das Problem schon an :-D

Weswegen ich auch mit der Umsetzung von maxcul für Pimatic angefangen habe. Da ich eine Komplette Installation hier habe, werde ich versuchen eine erste fertige Version zum Winter hin fertig zu haben.

Ich habe auch schon wieder einiges fertig, muss aber noch einige Fehler korrigieren bevor ich diese veröffentlichen kann.

So kann ich bereits die Fensterkontakte anlernen und abfragen, sowie die Thermostate mit der Basis pairen, allerdings noch nichts weiter. Das Problem ist, das ich viele Sachen erst aus unterschiedlichen Quellen analysieren, konzipieren und dann Asyncron Umsetzen muss. So ist mir der genaue Ablauf der Kommunikation zum Übertragen der Wochenprogramme nicht ganz klar. Aber ich hoffe ich kann dieses kleine Problem in nächster Zeit lösen.

Falls du da ein paar Tipps hast....ich bin für jede Hilfe dankbar :-)

Stay Tuned !!!

Flo

**Comment by sebastianha** [comment]
Hi,

klar, Deutsch geht natürlich auch :)

Das hört sich doch alles sehr gut an! Ich hatte leider noch zu wenig Zeit (wie immer) mich genauer mit PiMatic und den MAX-Geräten zu beschäftigen, aber vielleicht schaff ich es ja irgendwann.

Generell bin ich auch besser mit NodeJS/Javascript (CoffeeScript noch weniger) als mit Perl unterwegs und deswegen gefällt mir das PiMatic-Projekt einfach besser.

Jetzt gerade bastel ich erstmal an kleinen Sensoren, die ich dann auch einbinden möchte. Ich hatte das eigentlich für FHEM vor, aber wie du schon sagtest: Perl!

Anbei ein Foto von meiner aktuellen Sensor-Generation. 

![sensor_k](https://cloud.githubusercontent.com/assets/420807/9055375/e3bf7db0-3a8a-11e5-9d46-967e6576a5ed.jpg)

DHT22 für Temperatur und Luftfeuchtigkeit, ein BMP180 für Luftdruck (Temperatur ist da nochmal mit drin), interne Batterie-Messung und an den USB-Port kann man nochmal DS18B20 Temperatursensoren über 1-Wire anschließen. Das ganze kann per Micro-USB geladen werden und funkt den Spaß dann via 433MHz weg. Er sollte so nen Jahr mit einer Batterieladung halten wenn man alle 5 Minuten Daten überträgt.

**Comment by fbeek** [comment]
Ja das mit der Zeit ist immer so eine Sache :-D
Deine Module sehen echt gut aus. Kommt das Gehäuse aus einem 3D Drucker oder ist das was fertiges?

**Comment by sebastianha** [comment]
Das sind eigentlich so Do-It-Yourself USB-Handy-Akkus, die man für 3€ bei Ebay kaufen kann. Insgesamt kommt man auf so 15€ Materialkosten, wenn man alles direkt aus China bestellt.
