### ISSUE TITLE
Battery status shows only 0

### ISSUE THREAD

**Issue by S7EN** [fbeek/pimatic-maxcul#12]

**Comment by fbeek** [comment]
Do you have a device with an empty battery?
They send 0 if the battery is ok and 1 if the battery is low.
They do not measure the voltage.

It is only a boolean value if the battery is ok or not (in the Specs the data fields name is "battery low" so 0 is correct if everything is fine)

**Comment by fbeek** [comment]
Do you have a device with an empty battery?
They send 0 if the battery is ok and 1 if the battery is low.
They do not measure the voltage.

It is only a boolean value if the battery is ok or not (in the Specs the data fields name is "battery low" so 0 is correct if everything is fine)

**Comment by S7EN** [comment]
Okay, at first Installation the device showed "Ok" for Battery. After a while it showed the 0 and I thought this is a bug.

**Comment by fbeek** [comment]
Ah ok there could be a problem with the lable in the pimatic frontend not with the data. I will check this.

**Comment by fbeek** [comment]
This is fixed in v0.9.5

**Comment by georg90** [comment]
@fbeek I have a question for this one. In my installation the heating thermostats show ok/low just fine. However the contact sensors will show "ok" in the fronend, but the attribute will be 0 - So not too sure how to handle those in rules. Is it 0 or ok now? :)

Example:
![grafik](https://user-images.githubusercontent.com/6489464/28578987-994e4220-715b-11e7-95c1-19ed99d559d7.png)
![grafik](https://user-images.githubusercontent.com/6489464/28579033-b4556e36-715b-11e7-80d3-7eebb45f3930.png)
![grafik](https://user-images.githubusercontent.com/6489464/28579048-c09383e0-715b-11e7-839a-e2584bac94fd.png)

**Comment by fbeek** [comment]
Hello,

the bytes name in the protocol is "batterylow" so it is 1 if the battery is empty. So if you read 0 the battery should be ok.

**Comment by georg90** [comment]
I understand why it's 0, but I find it inconsistent to have it transformed in the frontend to ok, but use 0 in rules / in the variable. So it should be consistent with the implementation for the heating thermostats, doesn't it?

**Comment by fbeek** [comment]
Yes your are right, i will change the behavior to be consistent for all devices.

**Comment by fbeek** [comment]
Reopened for enhancement.

**Comment by georg90** [comment]
Thanks for taking care of this. It's a minor issue, but probably prevents some more issues coming in "Why is my rule not working.." ;-)

Keep up the good work!

**Comment by fbeek** [comment]
Should be fixed with v1.0.0
