### ISSUE TITLE
"(intermediate value)(...).catch is not a function" error

### ISSUE THREAD

**Issue by xCite1986** [fbeek/pimatic-maxcul#17]
by pressing the button “auto”, “manu” or “boost” i get an error:
https://usercontent.pimatic.org/1db2b56b380ae70cf2ba923fcb2e9f485d9d07d1/687474703a2f2f7777772e796f7573637265656e2e64652f736a6f64697862677331312e6a7067

https://forum.pimatic.org/topic/2483/pimatic-maxcul-and-max-cube-with-aculfw-acting-as-cul/21

**Comment by fbeek** [comment]
Hello. Sorry this is still work in progress but iam working on it

**Comment by fbeek** [comment]
This bug is now fixed in version 0.9.6
