### ISSUE TITLE
Can not get device ID in Debug Mode

### ISSUE THREAD

**Issue by S7EN** [fbeek/pimatic-maxcul#18]
i tried a few times but nothing happens in the logs when i enable debug mode in the plugin and try to pair the device. How can i get the device ID's?

**Comment by fbeek** [comment]
Have you restarted Pimatic after enabling the debug mode?  And have you enabled the maxcul or the pimatic debugging?
Have you activated the debug messages in the log view?

I have tested it here 10 minutes ago with the last master state.

**Comment by S7EN** [comment]
I restartet pimatic and then it worked. Thank you! Maybe you can write this in your Readme?
