### ISSUE TITLE
Heating Thermosthats does not show in third party apps

### ISSUE THREAD

**Issue by S7EN** [fbeek/pimatic-maxcul#19]
I mailed with the developer of "PimaticDroid" which is currently the best third party app for pimatic on the market. Everything works fine except my heating thermostats. The developer sais you don't use de default pimatic template with your plugin and thats why it does not show um in his app. Could you use it instead of your own template?

**Comment by fbeek** [comment]
No i can't use this template because of a special handling of the mode buttons and there is no possibility to show the config button without this.

At the moment there is no possibility to change this.
