### ISSUE TITLE
measurementOffset not working

### ISSUE THREAD

**Issue by medolino2009** [fbeek/pimatic-maxcul#20]
Changing value of measurementOffset is doing nothing... my temp is meassured about 2 C to high... i tried to correct this with measurementOffset -2 , but no change....

**Comment by fbeek** [comment]
Yes that is correct, as you can see in the code [Link](https://github.com/fbeek/pimatic-maxcul/blob/master/max-driver.coffee#L362) this is not supported at the moment, i will add this to the ToDo List and try to fix this in the next two weeks.

**Comment by medolino2009** [comment]
wow amazing... thanx for such a fast reaction. Best regards

**Comment by fbeek** [comment]
No problem :-)

Best Regards.

**Comment by fbeek** [comment]
Did you use the "transfer config" button to transfer the offset from the settings to the device itself? This is already implemented since a few month and should work. 

I am working on it so stay tuned.

**Comment by fbeek** [comment]
Here where some additional information for the offset handling, only for interest and documentation: 

If the internal temperature sensor is not well calibrated, it may produce a systematic error. Using measurementOffset, this error can be compensated. The reading temperature is equal to the measured temperature at sensor + measurementOffset. Usually, the internally measured temperature is a bit higher than the overall room temperature (due to closeness to the heater), so one uses a small negative offset. Must be between -3.5 and 3.5 degree celsius.

**Comment by medolino2009** [comment]
i just tried .... i get this error: received unknown data: LENERR

**Comment by medolino2009** [comment]
it's working.... i set -1.1 and not -1 first time...that's why i got error.... it works great... Can i remove config button when i change offset or button must stay here ? is this config inside of thermostat until it gets reset ?

**Comment by fbeek** [comment]
Morning,

Yes you can disable the Button. The config is saved im the thermostat.

If you have any further problems please contact me.

Kind Regards

**Comment by mwittig** [comment]
> Here where some additional information for the offset handling, only for interest and documentation:
> 
> If the internal temperature sensor is not well calibrated, it may produce a systematic error. Using measurementOffset, this error can be compensated. The reading temperature is equal to the measured temperature at sensor + measurementOffset. Usually, the internally measured temperature is a bit higher than the overall room temperature (due to closeness to the heater), so one uses a small negative offset. Must be between -3.5 and 3.5 degree celsius.

My suggestion is to add this to README

**Comment by mwittig** [comment]
> it's working.... i set -1.1 and not -1 first time...that's why i got error....

@fbeek Can you clarify this, please? Why is -1 not working? Having reviewed your code it should make no difference.


See also https://forum.pimatic.org/topic/4559/maxcul-measurementoffset-without-effect

**Comment by fbeek** [comment]
Hello @mwittig,

sorry for my late answer, i have not seen your request.
I will add the info to the readme.

I will check why -1 is not working.

Regards
