### ISSUE TITLE
After Pimatic update no response

### ISSUE THREAD

**Issue by S7EN** [fbeek/pimatic-maxcul#21]
After Pimatic update every heating thermostat gives no response. I have to use them manually.

**Comment by fbeek** [comment]
Mh that is strange.I updated yesterday and everything is working here. I checked the pimatic changes and there is no code that has anything todo with the plugin. So this cannot breake anything.

I will check the plugin another time but at the moment i cant  see anything wrong except your setup.

Have you any additional informations for me? Only with the info that it is not working i can not debbug anything.

Regards.

**Comment by S7EN** [comment]
I tried reboot pimatic and pi itself but nothing happened. Next try is to pair the devices again and see what happens.

**Comment by S7EN** [comment]
info [pimatic-maxcul]: Paket 0b01004000F0FF12f06e006c send but no response

This is the error, and unfortunately the LOVF Error pops up after two tries.

**Comment by fbeek** [comment]
Do you have ShutterContacts ?
Do they work on change?

Since you get the LOVF message the cul ist sending so there should be no problem with the plugin, because the codebase is the same and the pimatic update changes NOTHING that could interfere with the plugin and vice versa.

I think you have some other problem.
Have you implemented rules (like mentioned in an other issue) to check the thermostat temperature?
Eventually the thermostats have reached there transmissions limits and can receive but not respond.

**Comment by S7EN** [comment]
Hi, i do not have shutter contacts and rules. When i manually change the temperature of the thermostats, the temperature set point is given to pimatic but when i try to change the temperature in pimatic, i always get the not response error :(

**Comment by S7EN** [comment]
Here is a Debug Log when I try to reconnect one single thermostat. 

Protokolle
Debug, Info, Warn, Error
4

All

Showing 38 of 0 Messages
2017-01-14 10:40:25debug [pimatic-maxcul]: no packet to handle in send queue
10:40:25info [pimatic-maxcul]: Paket 0f01040300F0FF12f06e00110e0a284d send but no response!
10:40:22info [pimatic-maxcul]: received unknown data: LOVF
10:40:22debug [pimatic-maxcul]: incoming raw data from CUL: LOVF
10:40:22debug [pimatic-maxcul]: serial port buffer have been drained
10:40:22debug [pimatic-maxcul]: Send Packet to CUL: 0f01040300F0FF12f06e00110e0a284d, awaiting drain event
10:40:22debug [pimatic-maxcul]: Retransmit packet 0f01040300F0FF12f06e00110e0a284d, try 3 of 3
10:40:19info [pimatic-maxcul]: received unknown data: LOVF
10:40:19debug [pimatic-maxcul]: incoming raw data from CUL: LOVF
10:40:19debug [pimatic-maxcul]: serial port buffer have been drained
10:40:19debug [pimatic-maxcul]: Send Packet to CUL: 0f01040300F0FF12f06e00110e0a284d, awaiting drain event
10:40:19debug [pimatic-maxcul]: Retransmit packet 0f01040300F0FF12f06e00110e0a284d, try 2 of 3
10:40:16info [pimatic-maxcul]: received unknown data: LOVF
10:40:16debug [pimatic-maxcul]: incoming raw data from CUL: LOVF
10:40:16debug [pimatic-maxcul]: serial port buffer have been drained
10:40:16debug [pimatic-maxcul]: Send Packet to CUL: 0f01040300F0FF12f06e00110e0a284d, awaiting drain event
10:40:16debug [pimatic-maxcul]: Retransmit packet 0f01040300F0FF12f06e00110e0a284d, try 1 of 3
10:40:13info [pimatic-maxcul]: received unknown data: LOVF
10:40:13debug [pimatic-maxcul]: incoming raw data from CUL: LOVF
10:40:13debug [pimatic-maxcul]: serial port buffer have been drained
10:40:13debug [pimatic-maxcul]: Send Packet to CUL: 0f01040300F0FF12f06e00110e0a284d, awaiting drain event
10:40:13debug [pimatic-maxcul]: Updating time information for deviceId 12f06e
10:40:13debug [pimatic-maxcul]: got time information request from device 12f06e
10:40:13debug [pimatic-maxcul]: RSSI for Message : -59
10:40:13debug [pimatic-maxcul]: decoding Message Z0A000A0312F06E00F0FF001E
10:40:13debug [pimatic-maxcul]: incoming raw data from CUL: Z0A000A0312F06E00F0FF001E
10:40:10debug [pimatic-maxcul]: no packet to handle in send queue
10:40:10debug [pimatic-maxcul]: got OK-ACK Packet from 12f06e
10:40:10debug [pimatic-maxcul]: RSSI for Message : -59
10:40:10debug [pimatic-maxcul]: decoding Message Z0E01020212F06E00F0FF00011938391E
10:40:10debug [pimatic-maxcul]: incoming raw data from CUL: Z0E01020212F06E00F0FF00011938391E
10:40:09debug [pimatic-maxcul]: serial port buffer have been drained
10:40:09debug [pimatic-maxcul]: Send Packet to CUL: 0b01000100F0FF12f06e0000, awaiting drain event
10:40:09debug [pimatic-maxcul]: beginn pairing of a new device with deviceId 12f06e
10:40:09debug [pimatic-maxcul]: handling PairPing packet
10:40:09debug [pimatic-maxcul]: RSSI for Message : -60
10:40:09debug [pimatic-maxcul]: decoding Message Z1700040012F06E000000001001A14D4B46303034393331311C
10:40:09debug [pimatic-maxcul]: incoming raw data from CUL: Z1700040012F06E000000001001A14D4B46303034393331311C

**Comment by S7EN** [comment]
I solved it when i deleted the termostats and resetet them. After that i created them new in Pimatic.

**Comment by fbeek** [comment]
I analyzed the problem and there is no problem on the code side. You have the same LOFV Problem as in the other issue. In the time you recreated the devices there is simply a new time slot for transmission available to this works only until you reached the limit again.

Here is the explanation copied from the other issue :
 

> As i said in an other issue the LOFV means that you are sending to many packets. You could reach this limit very easily with only a few Devices.
> 
> Look here for a detailed definition [Link](https://wiki.fhem.de/wiki/LOVF).
> This is nothing that could be fixed by the Plugin, it is a rule given by law. The only possibility would be to change the message queue so that it saves the messages and retransmits them when there where new contingents available. But this would not change anything, because it only secures that the messages would be send later when there ist a new free timeslot.
> 
> Even with the original cube and the original software it can last over 5 hours to transfer the complete weekprogramm to ONE device, because of this stupid rule.
> 
> Your only option is to reduce the amount of packets send oder patch the cul firmware and remove the limit, which is not recommended an could be illegal.
