### ISSUE TITLE
Support for emitting the same state of an ECO button

### ISSUE THREAD

**Issue by sebastianha** [fbeek/pimatic-maxcul#22]
I just added an ECO button to my setup and I noticed that when it is "open" and I press "auto" (which will set the state to "open") this signal is not emitted again. This is due to the nature of pimatic ContactSensors (see pimatic/lib/devices.coffee line 511).

For me it would make sense that the ECO button emits it's state when pushed regardless of the previous state. Imagine you have two rules:
1) Press "AUTO" to set all thermostats to 20°
2) Press "ECO" to set all thermostats to 16°

This would work if you only use the button. But when you activated ECO mode and then changed the temperature of a thermostat by hand and just want to set all thermostats to ECO again this would not work as the button already is in ECO-state ("closed") and will not emit the state again.

Is there any chance to change this behaviour? Perhaps this is also a request which has to be forwarded to pimatic itself.

**Comment by fbeek** [comment]
Hello,

i will check this.
The only Problem is that i didn't have implemented this feature, i do not use the Eco Button and do not own anyone for testing.

**Comment by fbeek** [comment]
Should be fixed with v1.0.0
