### ISSUE TITLE
Respect ISM band 1% rule

### ISSUE THREAD

**Issue by Rootie** [fbeek/pimatic-maxcul#25]
The maxcul plugin should "resend" a packet when it receives a "LOVF" response from the cul device.

I started implementing this here:
[handle limit overflow](https://github.com/Rootie/pimatic-maxcul/pull/1)

I think the code for the server side works fine.

But on the client side the ajax request can run into a timeout.

A Possible solution would be to use an infinite timeout for the ajax request in `app/js/index.coffee`:
`@device.rest.changeTemperatureTo({temperatureSetpoint}, {global: no, timeout: 0})`
The downside is that this change would silence a real timeout. But I think this is a rare case and it is currently better to silence the timout.

Any optionions on this? Or probably a better solution?

**Comment by fbeek** [comment]
Hello Rootie, thank you for your help.

I checked your server side code and it looks fine to me.
Your FE solution can work, but I think an ajax request without an timeout and without user feedback is no good solution.

It takes up to 45 minutes until the next transmit slot is available, so the user thinks the command is send successfully but when the user checks the device there is no change, this is easily misunderstood and confusing.

**Comment by Rootie** [comment]
Well I am aware that this is not the "optimal" solution. But I think it is better than the current situation.
Let's compare how the plugin reacts to the limit overflow:

### Current situation:
Server side tries to send the packet 3 times and then shows a client error: 
```
Oops...
Paket 0bxxx send but no response!
```
The error message is not really true because the packet is not really sent.
Also it is not reliable. For example setting a temperature through a rule can easily fail and it the user won't recognize it until he/she comes into a cold/hot room.

### With proposed server side code
The reliability is highly increased because it retries until no lovf is returned.
The client shows a timeout error after the ajax request runs into a (browser default!) timeout, while the server is continuing to send the packet in the background. When an error happens now, the error will not be shown to the client.

### With proposed server side code and client side timeout set to infinite
Of course the server side reliability increase stays the same. The client waits until the packet is sent. And errors are shown during the whole time it needs to send the message. The only error that is not shown to the client would be a real timeout. But in this case most likely the whole connection is broken and pimatic itself would show an error.
The user can even see that the packet is not sent yet because the UI is in disabled state.
So no timeout does not mean no user feedback.


I my opinion the last case is the best of those three.

**Comment by fbeek** [comment]
yeah, ok you are right this is better than nothing.

I patched my module, so i had no problems with this.

If you do the changes i will merge them und make an new release.

**Comment by Rootie** [comment]
i created a pull request #26 with the changes

**Comment by fbeek** [comment]
Thank you for your help, i merged your pull request and published a new version
