### ISSUE TITLE
How do I use / pair devices

### ISSUE THREAD

**Issue by sebastianha** [fbeek/pimatic-maxcul#3]
Could you write some docu how to use your plugin?

I have a shutter contact and several thermostats here and would like to test/use the plugin but I am not able to pair the devices.

Thanks!

**Comment by fbeek** [comment]
Hey,

yes i am working on it.

I think i will release a new version until the next weekend. 

In the mean time you can find here some information: https://forum.pimatic.org/topic/1474/problem-while-installing-plugin-maxcul/12

**Comment by sebastianha** [comment]
Thanks, I already figured it out. I just listened for the pairing message in the logs and then edited the config.json accordingly.

At least the shutter works now, thanks for the good work!

**Comment by fbeek** [comment]
Thanks an have fun with it :-)
