### ISSUE TITLE
BitSet.js update

### ISSUE THREAD

**Issue by infusion** [fbeek/pimatic-maxcul#31]
Hi,

I'm the author of the bitset.js library you use. I just got the shorter npm name "bitset" instead of "bitset.js". The latter is now deprecated. Could you please update your dependencies? 

Thanks and sorry for any inconveniences
Robert

**Comment by fbeek** [comment]
Hello Robert,

thank you for the information.
I updated the dependencies with the new version.

Regards 
Florian

**Comment by mwittig** [comment]
Well, some more changes are required, see my PR #32
