### ISSUE TITLE
info [pimatic-maxcul]: Error in handleIncommingMessage Function, command : ThermostatState, error: TypeError: rawBitData.getRange is not a function

### ISSUE THREAD

**Issue by S7EN** [fbeek/pimatic-maxcul#33]
Hi,

when i try to control my thermostats i always get this error and nothing changed. I can't control them yet because of this.

info [pimatic-maxcul]: Error in handleIncommingMessage Function, command : ThermostatState, error: TypeError: rawBitData.getRange is not a function

**Comment by fbeek** [comment]
Hello,

thanks for the info.
I already fixed the issue and version v1.0.3 is now available.
