### ISSUE TITLE
Max Thermostats switch to Auto

### ISSUE THREAD

**Issue by Hansjshx** [fbeek/pimatic-maxcul#34]
Some of my Max Thermostats switch to Auto without a reason. Works as it should for a couple of days, then some of them switch back to Auto. I use them with Chronotherm.

**Comment by S7EN** [comment]
i have the same problem. It switches randomly and sometimes when i switch manually to eco or comfy nothing happens.

**Comment by fbeek** [comment]
I have found anorher error in combination with the bitset library, i will release a fixed version tomorrow.

**Comment by S7EN** [comment]
thank you for your work :)

**Comment by fbeek** [comment]
No problem :)

**Comment by fbeek** [comment]
Should be fixed with v1.0.4
