### ISSUE TITLE
Get errors when adjusting the temperature

### ISSUE THREAD

**Issue by Speedymax02** [fbeek/pimatic-maxcul#41]
Hello,
I'm using this nanoCUL: https://www.ebay.de/itm/nanoCUL-USB-Stick-FTDI-CC1101-868MHz-FW-1-67-SMA-Knick-Antenne-FHEM-CUL-868-/372206264709
I set the application in debug mode and looked for the thermostat from the device site. I put the thermostat in the pairing mode. However, Pimatic could not find anything. I tried this with different thermostats.
What am I doing wrong?
Best regards

**Comment by fbeek** [comment]
Hello,

do you have configured the correct serial port in the plugin? Or multiple usb to uart devices?

Best regards

**Comment by Speedymax02** [comment]
Hello,

thank you for your answer. I configured the plugin correct:
serial port: /dev/serial/by-path/platform-20980000.usb-usb-0:1.4:1.0-port0
I tried the CUL with my Windows computer, it was working. What other things can I do?

Best regards

**Comment by snowdej** [comment]
hi

mine only worked using /dev/ttyUSB0

I did clone my max cube address too so I did not have to pair them with a reset

jools

**Comment by Speedymax02** [comment]
Hi,

many thanks for your help.

I tried the plugin again under pimatic 0.9.42 here it finds my thermostats. Now I have the problem that, no matter which thermostat, I always get the following error messages when I try, for example, to change the temperature:

`2018-11-05 20:13:40 info [pimatic-maxcul]: Paket 0f0104401234560ae772wohnzimmer62 send but no response!`
`20:13:37 info [pimatic-maxcul]: received unknown data: LENERR`
`20:13:34 info [pimatic-maxcul]: received unknown data: LENERR`
`20:13:31 info [pimatic-maxcul]: received unknown data: LENERR`
`20:13:28 info [pimatic-maxcul]: received unknown data: LENERR`

Am I doing something wrong?

Best regards

**Comment by fbeek** [comment]
Hi,

as you can see in the logging message there is something wrong with the packet that will be send. 
0f0104401234560ae772wohnzimmer62 is not a valid packet.

The string "wohnzimmer" is not correct here as the packet should only contain hexadecimal character.
I think you have configured something wrong with the device ids.

Can you please provide your configuration for the device and the plugin itself.

Best regards
