### ISSUE TITLE
Could not parse expression on FakeWallThermostat

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [fbeek/pimatic-maxcul#42]
When i'm creating or editing a FakeWallThermostat, it outputs the following error:

`error [pimatic-maxcul]: Error on device 222222: Could not parse expression`

**Comment by treban** [comment]
probably the parameter    **refTemp**   is not valid. 

the example ist "$tempsensor.temperature"

refTemp must be set to a **valid variable**
-> This is designed to use a real temperature variable.
