### ISSUE TITLE
Loop with wrong Response

### ISSUE THREAD

**Issue by smarthomeagentur** [fbeek/pimatic-maxcul#44]
I get a send-loop if the response from the cul-stick is not valid. 
https://pastebin.com/D0V4Qgx0
There should be a limit of re-sending I think. The Thermostat works (sending to it) fine but the CC1101 Module from my stick is not able to receive (hardware issue I think). So the Plugin should be able to handle it.

**Comment by fbeek** [comment]
Your CUL is sending a LOVF Message, this means it has reaches it transmit limit and has not send any package.
If the plugins gets this it leaves the message in the queue for later transmission when the cul has new send credits available. So no message gets lost. Please look in the other closed Issues or the readme for the 868MHz Band 1% transmit limit in the EU.

Would your cul aknowlege the send but cannot receive any returning mesaage from the device the plugin would delete the message after 3 retries.

So everything ist correct.
