### ISSUE TITLE
pairing maxcul with heatingthermostat

### ISSUE THREAD

**Issue by uli-2016** [fbeek/pimatic-maxcul#5]
*\* I have a problem with pairing / connection to devices **
-> see my maxcul.log:
12:14:37.615 [pimatic-maxcul] debug: got data -> Z1700040013093B000000001001A14D455131343432343638
12:14:37.629 [pimatic-maxcul] debug: decoding Message Z1700040013093B000000001001A14D455131343432343638
12:14:37.638 [pimatic-maxcul] debug: handling PairPing packet
12:14:37.647 [pimatic-maxcul] debug: beginn pairing of a new device with deviceId 13093b
12:14:37.659 [pimatic-maxcul] info: Send Packet to CUL: 0B02000112345613093B0000
12:14:37.659 [pimatic-maxcul] info:>
01 123456 13093b 00 00 00
12:14:37.700 [pimatic-maxcul] info: send done !
12:14:38.726 [pimatic-maxcul] debug: got data -> Z0E02020213093B1234560001190028
12:14:38.734 [pimatic-maxcul] debug: decoding Message Z0E02020213093B1234560001190028
12:14:38.739 [pimatic-maxcul] debug: got OK-ACK Packet from 13093b

*\* it seems the pairing is right..... but a little bit later: **
12:21:50.104 [pimatic-maxcul] debug: got data -> Z0A000A0313093B12345600
12:21:50.112 [pimatic-maxcul] debug: decoding Message Z0A000A0313093B12345600
12:21:50.117 [pimatic-maxcul] debug: got time information request from device 13093b
12:21:50.124 [pimatic-maxcul] debug: Updating time information for deviceId 13093b
12:21:50.193 [pimatic-maxcul] info: Send Packet to CUL: 0F04040312345613093B0010140C15F2
12:21:50.193 [pimatic-maxcul] info:>
03 123456 13093b 10140c15f2 00 04
{ length: 10,
  msgCnt: 0,
  msgFlag: 10,
  groupid: 0,
  msgTypeRaw: '03',
  src: '13093b',
  dest: '123456',
  rawPayload: '',
  forMe: true,
  decodedCmd: 'TimeInformation' }
12:21:50.214 [pimatic-maxcul] info: send done !

*\* and ...**
12:21:51.263 [pimatic-maxcul] debug: got data -> Z0E04020213093B1234560001190028
12:21:51.270 [pimatic-maxcul] debug: decoding Message Z0E04020213093B1234560001190028
12:21:51.276 [pimatic-maxcul] debug: got OK-ACK Packet from 13093b
12:21:52.057 [pimatic-maxcul] debug: got data -> Z0F00046013093B0000000019002800F2
12:21:52.064 [pimatic-maxcul] debug: decoding Message Z0F00046013093B0000000019002800F2
{ CCCCC: '\u0019' } { length: 15,
  msgCnt: 0,
  msgFlag: 4,
  groupid: 0,
  msgTypeRaw: '60',
  src: '13093b',
  dest: '000000',
  rawPayload: '19002800F2',
  forMe: false,
  decodedCmd: 'ThermostatState' }

*\* the TimeInformation seems to be correctly but ThermostatState not yet **
and the devices description on pimatic is gray not black....

**Comment by fbeek** [comment]
Hello,

for the version that is available that is all correct.
As i said already in the Pimatic forum the ThermoState is not implemented yet.

I am working on it, at the moment you can create the device but there are no functions.
The device can only pair and get the time from the server.

**Comment by uli-2016** [comment]
thanks for your info, I can wait for new functions, but I'm interested in.

**Comment by fbeek** [comment]
Fixed in 0.2.5
