### ISSUE TITLE
Pairing does not work?

### ISSUE THREAD

**Issue by sebastianha** [fbeek/pimatic-maxcul#7]
Hi,

I just updated the plugin to the latest version and tried to pair my thermostat. I enabled pairing mode in my config and I added the thermostat as shown in the readme.

When I reset my thermostat and run the installation process I get the following in the logs:

```
19:29:47.722 [pimatic-maxcul] from CUL -> ZXXX...
19:29:47.737 [pimatic-maxcul] decoding Message ZXXX...
19:29:47.753 [pimatic-maxcul] handling PairPing packet
19:29:47.767 [pimatic-maxcul] beginn pairing of a new device with deviceId XXXXXX
19:29:47.782 [pimatic-maxcul] Send Packet to CUL: XXX...
19:29:47.782 [pimatic-maxcul]>
19:29:47.817 [pimatic-maxcul] send done !
```

But then I do not receive any more message and I cannot control the thermostat. Also at the thermostat the antenna icon does not appear.

Am I doing something wrong?

**Comment by fbeek** [comment]
Hi,

on first look everything looks fine.
Can you send me a copy of your plugin ans device config?

Does the thermostat later requests time informations from the server?

Eventualy there is a problem with the annoying 1% rule for the 868Mhz band in the MAX Cul.

At the time where i used FHEM i patched it out of my culs firmware...else the programming process for the devices via the cul can consume multiple hours.

**Comment by sebastianha** [comment]
Plugin Config:

```
    {                                                                                                                                              
      "plugin": "maxcul",                                                                                                                          
      "serialPortName": "/dev/ttyUSB1",                                                                                                            
      "baudrate": 38400,                                                                                                                           
      "homebaseAddress": "XXXXXX",                                                                                                                 
      "enablePairMode": true                                                                                                                       
    }
```

Device Config:

```
{
      "class": "MaxculShutterContact",
      "id": "max-shutter-XXXXXX",
      "name": "MAX Shutter Contact (XXXXXX)",
      "deviceId": "XXXXXX"
    },
    {
      "id": "max-thermostat-XXXXXX",
      "class": "MaxculHeatingThermostat",
      "name": "Max Thermostat (XXXXXX)",
      "deviceId": "XXXXXX",
      "groupId": "00",
      "guiShowModeControl": true,
      "guiShowPresetControl": true,
      "guiShowTemperatureInput": true,
      "guiShowMeasuredTemperature": true,
      "guiShowBatteryState": true,
      "guiShowConfigButton": true,
      "ecoTemp": 17,
      "comfyTemp": 20,
      "minimumTemperature": 4.5,
      "maximumTemperature": 30.5,
      "measurementOffset": 0,
      "windowOpenTime": 60,
      "windowOpenTemperature": 4.5
    }
```

As far as I remember I also removed the 1% restriction from my Arduino-Cul-Stick.

I only see the first request for pairing then nothing more is visible in the log.

**Comment by fbeek** [comment]
Hi,

on first sight everything looks fine with your config.

Did you a hardreset or softreset (only battery) of you thermostat?
Do you have a FHEM instance running in the background?
With that i had the same problems.

Is your debug mode enabled?

**Comment by sebastianha** [comment]
Hi,

I did a hard reset (inserting batteries while pressing all three buttons)
Currently there is no FHEM running
Debug mode is enabled, there I saw the pairing message.

But at the end there are no more messages.

I am using an Arduino CUL, perhaps I need to reflash it.

Which thermostat versions are you using? I have 1.6 and 1.8 here.

**Comment by sebastianha** [comment]
I did some more research and also tried another nanoCul Stick but with the same result. I only get the first pairing message and nothing more.

I personally think that the stick does not send anything out but I need to verify this.

One thing I noticed is, that the arduino needs some time to initialize, so I added a timeout after opening the serial connection.

Do you have any idea what could be wrong?

**Comment by fbeek** [comment]
Hey. 

thank you for your informations.

I have both versions of the thermostats. And CUL firmware 1.6 with auto ack feature.

Unfortunaly i can first investigate this any further in the next week.

But the problem colan be the init part of the Cul.

**Comment by sebastianha** [comment]
Thanks for looking at it.

I will also try to investigate the problem.

**Comment by sebastianha** [comment]
Do I have to enable the auto ack feature of the cul stick manually?

If there is some time I will try to pair the thermostat with fhem first and then test it with the pimatic plugin. Perhaps there is some problem with the pairing process.

**Comment by fbeek** [comment]
No, the maxcul driver will handle this for you.

After my last release i paired 4 Shutters and 4 thermostats without any problems from the hard reset state because of problems with my base id (they were different on dev an production system).

Is your stick an original Busware Stick or a copy? With some AVR USB devices i have had problems in the past if there where connected to the Rpi USB Ports.

**Comment by sebastianha** [comment]
I have an self-assembled Arduino + CC1101 "stick".

It worked fine with FHEM

**Comment by sebastianha** [comment]
...everything my fault, please forgive me.

I did a reset of the device but also a manual pairing was needed by holding down the boost-button for a longer time. I totally forgot about this...

Now it's working, keep up the great work!

**Comment by fbeek** [comment]
No Problem :-)

Thank you, and if you have another problem, please don't hesitate to contact me
