### ISSUE TITLE
Kann unter pimatic 0.9 nicht installiert werden

### ISSUE THREAD

**Issue by w00dst0ck** [fbeek/pimatic-maxcul#9]
Habe einen Raspberry Pi 3 mit Raspbian im Einsatz und kann das Plugin nicht installieren.
Im Pimatic Log findet sich folgender Eintrag:
`[pimatic]: Error installing plugin pimatic-maxcul: Error running "./node_modules/pimatic/ppm.js install pimatic-maxcul@0.4.1 --unsafe-perm"`

Beim manuellen Installieren über NPM gibt es Meldungen über Probleme mit dem hipack package.

`$ sudo npm install --unsafe-perm pimatic-maxcul

npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm" "pimatic-maxcul"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! hipack@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hipack@1.0.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hipack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hipack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log`

**Comment by fbeek** [comment]
Hallo, 

leider ist pimatic-maxcul noch nicht 0.9 kompatible.
Ich arbeite momentan erst noch an einer neuen Treiberschicht für das CUL Modul.

Im Anschluss daran, werde ich mit der Umsetzung des 0.9 Supports beginnen. Bis zur Fertigatellung des 0.9 Supports wird es wohl noch 2 Monate dauern.

MFG

fbeek

**Comment by w00dst0ck** [comment]
Könnte dies eine Alternative zu hipack sein?
http://locutus.io/php/misc/pack/

**Comment by fbeek** [comment]
Hey,

Danke für die Info. Ich habe gerade eine alternative implementiert, mit binary-parser und ein bisschen node Magie :-D

Werde das jetzt noch genauer testen und dann Morgen ein Update für die 0.8er Version von Pimatic bereitstellen. Ich hoffe in der nächsten Woche den 0.9 Support freigeben zu können.

Danke nochmal für deine Info.

**Comment by fbeek** [comment]
Die neue Version mit 0.9 Kompatibilität wurde released . Sollte es noch weitere Probleme geben erstelle bitte einfach ein neues Ticket.
